[package]
name = "tsubame"
version = "0.0.1"
authors = ["azusachino <azusa146@gmail.com>"]
edition = "2021"
readme = "README.md"
license-file = "LICENSE"
repository = "https://github.com/azusachino/tsubame"

[dependencies]
tsubame_lib = { path = "../lib" }

anyhow = "1"
axum = "0.7"
dotenv = "0.15"
serde = "1.0"
serde_derive = "1"
serde_json = "1"
sqlx = { version = "0.8", features = [
    "runtime-tokio-rustls",
    "any",
    "postgres",
] }
tokio = { version = "1.23", features = ["full"] }
toml = "0.8"
tonic = "0.12"
prost = "0.13"

# alloc
tikv-jemallocator = "0.6"

[build-dependencies]
tonic-build = "0.12"

[profile.dev]
opt-level = 0
overflow-checks = false # Disable integer overflow checks.
